include:
  # peripherals
  - board: nice_nano_v2
    shield: charybdis_left

    # for dongle setup
    #cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano_v2
    shield: charybdis_right

    #for dongle setup
    #cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

    # for zmk studio(remove for dongle setup)
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # dongle
  - board: nice_nano_v2
    shield: charybdis_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # bt settings reset
  - board: nice_nano_v2
    shield: settings_reset
